#!/bin/bash
filename='/home/bitnami/frcopengrok/repolist'
repostore='/var/opengrok/src-real'
echo Start
if [ ! -d ${repostore} ]; then
	mkdir ${repostore}
fi
cd ${repostore}
while read url acc repo branch; do
	echo "cloning ${url}"
	git clone ${url} ${acc}-${repo}-${branch}
done < $filename
