#!/bin/bash

# Make sure dtags file is writeable.
if [ -f /var/opengrok/data/index/dtags.eftar ]; then
	sudo chmod g+rw /var/opengrok/data/index/dtags.eftar
fi
if [ -d /var/opengrok/data/index ]; then
	sudo chmod g+rw /var/opengrok/data/index
fi
# Tell the server about the paths file
curl -i -X POST -H "Content-Type: application/json" \
  --data "@/var/opengrok/etc/paths.json" \
  http://localhost:8080/source/api/v1/system/pathdesc
# fix the permissions and group
sleep 5
/home/bitnami/bin/fixdataperms
