#!/bin/bash

# Make sure dtags file is writeable.
if [ -f /var/opengrok/data/index/dtags.eftar ]; then
	sudo chmod a+rw /var/opengrok/data/index/dtags.eftar
fi
# Tell the server about the paths file
curl -i -X POST -H "Content-Type: text/plain" \
  --data-binary "@/var/opengrok/etc/paths.tsv" \
  http://localhost/source/api/v1/system/pathdesc
