#!/bin/bash
function  ogg() {
	if [ $# -eq  0 ]
	then
		opengrok-groups -a ~/opengrok/lib/opengrok.jar -- -e
	fi
	if [ $# -eq  1 ]
	then
		opengrok-groups -a ~/opengrok/lib/opengrok.jar -- -i c.xml -o c.xml \
			-n "$1"
	fi
	if [ $# -eq  2 ]
	then
		opengrok-groups -a ~/opengrok/lib/opengrok.jar -- -i c.xml -o c.xml \
			-n "$1" -r "$2"
	fi
	if [ $# -eq  3 ]
	then
		opengrok-groups -a ~/opengrok/lib/opengrok.jar -- -i c.xml -o c.xml \
			-n "$1" -r "$2" -p "$3"
	fi

}

ogg > c.xml
ogg "FIRST-WPI"
 ogg "WPI API Robot Programming" "allwpilib|opencv" "FIRST-WPI"
 ogg "WPI Other" "frc-characterization|frc-docs|GradleRIO|OutlineViewer|PathWeaver|roboRIOVisionExamples|RobotBuilder|shuffleboard|SmartDashboard|sysid|toolchain-builder|vendor-template|VisionBuildSamples|vscode-wpilib|wpimath|wpiutil|wpilib-version-plugin|WPILibPi" "FIRST-WPI"
ogg "Python"
 ogg "robotpy" "pyfrc|robotpy-wpilib|robotpy-wpilib-utilities|pynetworktables" "Python"
ogg "Team Robots"
 ogg "FRC151" "FRC151-2018-PowerUp|FRC151-ShowBot2018|FRC151-DeepSpace2019|FRC151-InfiniteRecharge2020|FRC151-RapidReact2022" "Team Robots"
ogg "Team Tools" "Pathfinder|FRC1014-badlog|FRC1540-ROOSTER|FRC2521-sertain"
ogg "Vendor Tools"
 ogg "CTR Electronics" "Phoenix-Examples-Languages|Phoenix-api" "Vendor Tools"
 ogg "Oracle" "opengrok" "Vendor Tools"
mv c.xml /var/opengrok/etc/read-only.xml
