#!/bin/bash
function  ogg() {
	if [ $# -eq  0 ]
	then
		opengrok-groups -a ~/opengrok/lib/opengrok.jar -- -e
	fi
	if [ $# -eq  1 ]
	then
		opengrok-groups -a ~/opengrok/lib/opengrok.jar -- -i c.xml -o c.xml \
			-n "$1"
	fi
	if [ $# -eq  2 ]
	then
		opengrok-groups -a ~/opengrok/lib/opengrok.jar -- -i c.xml -o c.xml \
			-n "$1" -r "$2"
	fi
	if [ $# -eq  3 ]
	then
		opengrok-groups -a ~/opengrok/lib/opengrok.jar -- -i c.xml -o c.xml \
			-n "$1" -r "$2" -p "$3"
	fi

}

ogg > c.xml
ogg "FIRST-WPI"
 ogg "WPI API Robot Programming" "allwpilib|CANJaguar|cscore|nivision|ntcore|opencv|riolog|wpiutil" "FIRST-WPI"
 ogg "WPI Other" "branding|build-tools|design-docs|DocumentationBuilder|EclipsePlugins|java-installer|OutlineViewer|roborio-ant-tasks|roboRIOVisionExamples|RobotBuilder|sfx|sfx-livewindow|shuffleboard|SmartDashboard|SmartDashboard-Extensions|styleguide|toolchain-builder|vendor-template|VisionBuildSamples|wpilib-version-plugin|zulu-jre-ipk" "FIRST-WPI"
ogg "Python"
 ogg "robotpy" "pyfrc|robotpy-wpilib|robotpy-wpilib-utilities|pynetworktables" "Python"
ogg "Team Robots"
 ogg "FRC151" "FRC151-2018-PowerUp|FRC151-ShowBot2018|FRC151-DeepSpace2019" "Team Robots"
ogg "Team Tools" "Pathfinder|FRC2521-sertain"
ogg "Vendor Tools"
 ogg "CTR Electronics" "Phoenix-Examples-Languages|Phoenix-api" "Vendor Tools"
mv c.xml /var/opengrok/etc/read-only.xml
