#!/bin/bash
cd ~
git clone  https://github.com/universal-ctags/ctags.git
if [ ! -d ctags ]; then
	wget https://github.com/universal-ctags/ctags/archive/master.zip
	unzip master.zip
	mv ctags-master ctags
fi
cd ctags/
./autogen.sh
./configure
make
sudo make install
