#!/bin/bash

cd ~
latestog_url=`curl -s https://api.github.com/repos/oracle/OpenGrok/releases | grep browser_download_url | head -1 | sed -e 's/^.*https/https/' -e 's/"$//'`
latestog_file=`basename $latestog_url`
latestog_dir=`echo $latestog_file | sed -e 's/.tar.gz//'`
if [ ! -f $latestog_file ]; then
	wget $latestog_url
	gunzip -c $latestog_file | tar xf - 
	if [ -L opengrok ]; then
	       	rm opengrok
	fi
	ln -s $latestog_dir opengrok
fi
ls -l opengrok
cd opengrok/tools
sudo python3 -m pip install open*gz | grep -v "already satisfied"
# Update style.css in war file before deploying.
~/frcopengrok/fixstyle
sudo -u tomcat opengrok-deploy ~/opengrok/lib/source.war ${OPENGROK_TOMCAT_BASE}/webapps/source.war
echo
echo Deploy done.
echo After starting Tomcat you need to run:
echo   ~/frcopengrok/copylogo
echo   ~/frcopengrok/confpaths
echo
