#!/bin/bash -xv

opengrok-indexer \
   -C \
   -J='-Xmx12G' \
   -J='-server' \
   -J="-Djava.util.logging.config.file=${OPENGROK_INSTANCE_BASE}/etc/logging.properties" \
   -a ${OPENGROK_DISTRIBUTION_BASE}/opengrok.jar -- \
   -s "${OPENGROK_INSTANCE_BASE}/src" \
   -d "${OPENGROK_INSTANCE_BASE}/data" \
   ${OPENGROK_READ_XML_CONFIGURATION:+-R} ${OPENGROK_READ_XML_CONFIGURATION} \
   --renamedHistory off \
   --leadingWildCards on \
   --memory 256 \
   -H \
   -P \
   -S \
   -W ${OPENGROK_INSTANCE_BASE}/etc/configuration.xml
