#!/bin/bash

# if /tmp/noshutdown exists, don't shutdown
if [ -f /tmp/noshutdown ]; then
	exit
fi
# if /tmp/resyncrunning exists, don't shutdown
if [ -f /tmp/resyncrunning ]; then
	exit
fi
nearboot=`cat /proc/uptime | sed -e 's/ .*//'`
nearboot=`printf "%.0f" ${nearboot}`
# no shutting down for first 5 minutes
if [ 300 -ge ${nearboot} ]; then
	exit
fi
# Look for logs less than X minutes old.
LOGS=`/home/bitnami/bin/logage.pl`
# Is anyone logged in? Don't want to terminate a session
WHO=`who`
# Did we find any?
if [[ ! -z "${LOGS}${WHO}" ]]; then
	# Yep, nothing to do, just keep running.
	echo `date` ${WHO} ${LOGS} > /tmp/lastcheck
	exit;
fi
# No logs for the last period of time. Time to sleep.
echo `date` ${WHO} ${LOGS} > /var/tmp/shuttingdown
/opt/bitnami/ctlscript.sh stop
/sbin/shutdown +0 System idle shutting down.
