#!/bin/bash

sudo mkdir /var/opengrok
sudo chown bitnami /var/opengrok
mkdir /var/opengrok/etc
cp ~/opengrok/doc/logging.properties /var/opengrok
opengrok-groups -a ~/opengrok/lib/opengrok.jar -- -e > /var/opengrok/etc/configuration.xml
./cloneall
./index-first
cp header_include footer_include /var/opengrok/data
