#!/bin/bash
trap '{ rm /tmp/resyncrunning ; exit 1; }' INT
touch /tmp/resyncrunning
echo `date` starting  >> /var/tmp/resync
time opengrok-sync -f -c /var/opengrok/etc/sync.conf --uri http://localhost/source -d /var/opengrok/src >> /var/tmp/resync 2>>&1
rm /tmp/resyncrunning
echo `date` ended >> /var/tmp/resync
