#!/bin/bash
# Adapted to use HEAD rather than the new commit ref
get_file_rev() {
    git rev-list -n 1 HEAD "$1"
}

update_file_timestamp() {
    file_time=`git show -s --pretty=format:%ai "$(get_file_rev "$1")"`
    sudo touch -d "$file_time" "$1" >> /tmp/timestamps.$$
}

# Loop through and fix timestamps on all files in our CDN directory
old_ifs=$IFS
IFS=$'\n' # Support files with spaces in them
for file in $(git ls-files)
do
    update_file_timestamp "${file}"
done
IFS=$old_ifs
